INSERT INTO MEMBER(NAME,PASSWORD,EMAIL) VALUES ('KING','1234','KING@EMAIL.COM');
INSERT INTO MEMBER(NAME,PASSWORD,EMAIL) VALUES ('KIM','1234','KIM@EMAIL.COM');
INSERT INTO MEMBER(NAME,PASSWORD,EMAIL) VALUES ('EOM','1234','EOM@EMAIL.COM');