DROP TABLE IF EXISTS MEMBER;

CREATE TABLE MEMBER(
    NO               INT             PRIMARY KEY    AUTO_INCREMENT,
    NAME        VARCHAR(255)    NOT NULL,
    PASSWORD    VARCHAR(255)    NOT NULL,
    EMAIL       VARCHAR(255)
);
