server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
spring:
  devtools:
    livereload:
      enabled: true
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:mybatis-test
    username: plid
    password: 1234
    hikari:
      maximum-pool-size: 4

  sql:
    init:
      data-locations: "classpath*:h2query/data.sql"
      schema-locations: "classpath*:h2query/schema.sql"



mybatis:
  mapper-locations: config/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      plidservice:
        support:
          mapper=TRACE:


